version: "3.8"

services:
  asterisk:
    platform: linux/amd64
    build: .
    container_name: asterisk
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: Asia/Kolkata
    volumes:
      - ./config:/etc/asterisk/:rw
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8088/httpstatus || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
